### PR TITLE
Add support for https site urls in Cheffile

### PR DESCRIPTION
**Pull request by databus23**

### CODE REVIEW

**Comment by databus23** [comment]
Oh, I just saw #18. So consider this a bump for #18. :)

**Comment by bozinsky** [comment]
+1

**Comment by tlesmann** [comment]
+1

**Comment by Kuckkuck** [comment]
+1

**Comment by Afterglow** [comment]
+1

**Comment by sl4m** [comment]
PR #18 has been merged, so this can be closed.

**Comment by yfeldblum** [comment]
Thanks for the bumps!

**Pull request closed without merging**
